apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base-application/ui
  - ../../../../base-application/catalog
patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: to_be_ignored
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: eks.amazonaws.com/compute-type
                      operator: In
                      values:
                      - hybrid
  - target:
      kind: StatefulSet
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: to_be_ignored
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: eks.amazonaws.com/compute-type
                      operator: In
                      values:
                      - hybrid
