affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: In
          values:
          - hybrid
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 25
    clusterPoolIPv4PodCIDRList:
    - 10.53.0.0/16
operator:
  replicas: 1
  unmanagedPodWatcher:
    restart: false
bgpControlPlane:
  enabled: false
routingMode: native
ipv4NativeRoutingCIDR: 10.0.0.0/8
enableIPv4Masquerade: true
